<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.0.0.309
*/

require_once('form_process.php');

$form = array(
	'subject' => 'MAIN Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Selected',
		'checkbox_unchecked' => 'Unselected',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'tihonova_regina@mail.ru',
		'to' => 'tihonova_regina@mail.ru'
	),
	'fields' => array(
		'custom_U449' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Как Вас зовут?',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Как Вас зовут?\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Ваш Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Ваш Email\' is required.',
				'format' => 'Field \'Ваш Email\' has an invalid email address.'
			)
		),
		'custom_U458' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Сообщение',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
